---
- name: read password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password

- name: Install suggested plugins (multiple - based on the list)
  jenkins_plugin:
    name: "{{ item }}"
    url_username: admin
    url_password: "{{ jenkins_password.stdout }}"
    url: http://localhost:8080
  with_items: "{{ jenkins_plugins }}"

- name: Print Credential
  debug:
    msg: "Username: admin , Password: {{ jenkins_password.stdout }}"