---
- hosts: all
  become: true
  pre_tasks:
  - name: apt update
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  tasks:
  - name: Install packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - git
    when: ansible_os_family == "Debian"


- hosts: jenkins
  gather_facts: false
  become: true
  tasks:
  - name: Download Jenkins GPG key
    get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc
      mode: '0644'

  - name: Add Jenkins repository
    apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins

# install java 17 task
  - name: Install Java 17
    apt:
      name: openjdk-17-jdk
      state: present

# install jenkins task
  - name: Install Jenkins
    apt:
      name: jenkins
      state: present

  - name: Start Jenkins
    service:
      name: jenkins
      state: started
      enabled: yes
    register: jenkins_service


  - name: Wait for Jenkins to start
    uri:
      url: http://localhost:8080
      status_code: 200
    register: result
    until: result.status == 200
    retries: 60
    delay: 5
    when: jenkins_service.changed

  - name: Configure Jenkins plugins
    include_role:
      name: jenkins_plugins
    when: jenkins_service.changed and result.status == 200