---
- hosts: localhost
  become: true
  gather_facts: false
  tasks:
  - name: Print Registered Valuse of a Module
    service:
      name: sshd
      state: started
    register: results
  - name: print results
    debug:
      msg: "{{ results }}"
